PAYMENT_CHOICES = (
    ('ORANGE MONEY (OM)', 'ORANGE MONEY'),
    ('MOBILE MONEY (MM)', 'MOBILE MONEY'),
    ('USDT (TETHER)', 'USDT (TETHER)'),
    ('BITCOIN (BTC)', 'BITCOIN (BTC)'),
    ('Tron (TRC20)', 'Tron (TRC20)')
)