# Generated by Django 4.0 on 2022-03-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='desc',
            new_name='content',
        ),
    ]
