# Generated by Django 4.0 on 2022-03-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_rename_desc_service_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
