# Generated by Django 4.0 on 2022-03-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_messagaservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessagaService',
            new_name='MessageService',
        ),
    ]
