# Generated by Django 4.0 on 2022-04-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_rename_messagaservice_messageservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', help_text='Upload a product image', upload_to='images/'),
        ),
    ]
