# Generated by Django 4.0 on 2022-01-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_premium',
        ),
    ]
