# Generated by Django 4.0 on 2022-04-05 11:29

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_account_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
