# Generated by Django 4.0 on 2022-03-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_subscription_end_date_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='avatars'),
        ),
    ]
