# Generated by Django 4.0 on 2022-04-19 18:34

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('grade', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True)),
            ],
        ),
    ]
