# Generated by Django 4.0 on 2022-04-04 13:40

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
