# Generated by Django 4.0 on 2022-02-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_commentproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentproduct',
            name='name',
        ),
    ]
