# Generated by Django 4.0 on 2022-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payementmethode',
            name='name',
            field=models.CharField(choices=[('ORANGE MONEY (OM)', 'ORANGE MONEY'), ('MOBILE MONEY (MM)', 'MOBILE MONEY')], max_length=150, unique=True),
        ),
    ]
