# Generated by Django 4.0 on 2022-03-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_payementmethode_name_of_the_beneficiary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_key',
            new_name='id_trasaction',
        ),
    ]
