# Generated by Django 4.0 on 2022-04-20 14:25

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_payementmethode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payementmethode',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
