# Generated by Django 4.0 on 2022-06-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_alter_payementmethode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payementmethode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/qr_code/'),
        ),
    ]
