# Generated by Django 4.0 on 2022-03-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_rename_order_key_order_id_trasaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_trasaction',
            field=models.CharField(max_length=200, verbose_name='ID transaction'),
        ),
    ]
